### ISSUE TITLE
Feature Request | When NSFW is disabled in settings, show age gate for NSFW subreddits

### ISSUE THREAD

**Issue by Mennaruuk** [libreddit/libreddit#159]
**Is your feature request related to a problem? Please describe.**
Newcomers might be confused when visiting a NSFW subreddit. Currently, Libreddit just shows the side panel, with no posts. It might give the impression the subreddit is empty. On Reddit, an age gate is shown, giving the user a choice to either proceed (yes) or return to previous page (no).

**Describe the solution you'd like**
An age gate warning for those who have NSFW disabled in settings. This solution can feed two birds with one scone: on one hand, the user is shown an age gate. On the other hand, if the user says yes, then the yes button would lead to enabling NSFW in the settings and making it persist. This is how Reddit does it for non-signed-up users.
**Describe alternatives you've considered**
When I visit a new instance of Libreddit and check out a NSFW subreddit, I make sure to enable NSFW in settings so I can see the subreddit's content.

**Additional context**
This is how Libreddit currently handles NSFW subreddits when NSFW is disabled in settings.
![imageedit_2_3465049298](https://user-images.githubusercontent.com/52135169/111922284-5232dc80-8a6f-11eb-8f80-76ce98cde222.png)

**Comment by sigaloid** [comment]
Hi, what do you think of this? 

![image](https://user-images.githubusercontent.com/69441971/168181586-8651785c-ed82-4e20-8336-0392192188a1.png)

Currently I have it set to display if *any* posts in a subreddit are NSFW and hidden (and user has nsfw off). 

Unfortunately that means r/popular (home page) would show that warning at the top most of the time if any post is nsfw (usually at least one is). 

![image](https://user-images.githubusercontent.com/69441971/168182352-bfc90178-6b6b-42a2-9ba1-006536b68baf.png)


Maybe at the bottom is better. Alternatively, it can be set to display if *all* posts are NSFW but if there's a mixed sub someone may be confused why half the posts are showing. 

Unfortunately Reddit doesn't seem to have a single over_18 flag for an entire subreddit.

Perhaps this can be displayed in the sidebar rather...
