### ISSUE TITLE
Feature Request | Duplicates

### ISSUE THREAD

**Issue by Mennaruuk** [libreddit/libreddit#160]
**Is your feature request related to a problem? Please describe.**
On Reddit, there is this feature where if you replace the part of the url `comments` with `duplicates`, Reddit shows you duplicate threads about the same topic. On Libreddit, it says "Nothing here. Head back home?"

**Describe the solution you'd like**
Libreddit would show duplicates of a Reddit thread.

**Describe alternatives you've considered**
Currently, I go to Reddit in case I want to see duplicates of a thread.

**Additional context**
Example
https://www.reddit.com/r/news/duplicates/ma0gce/tennessee_man_loses_1_million_lottery_ticket_but/

**Comment by bnainar** [comment]
The duplicates should show
* Posts containing that link
* AND the crossposts of current post

**Comment by curlpipe** [comment]
Note to self:

API format is like this:

https://www.reddit.com/r/news/duplicates/ma0gce/tennessee_man_loses_1_million_lottery_ticket_but.json

**Comment by spikecodes** [comment]
Thanks! Merging this into #574
