### ISSUE TITLE
Fix line height of score and comment count

### ISSUE THREAD

**Issue by ghost** [libreddit/libreddit#179]
![IMG_20210406_191025](https://user-images.githubusercontent.com/59839368/113720364-2caeff80-970c-11eb-84b5-794f66e15b24.jpg)

The score count and comment count are not in the same line. One is higher

**Comment by curlpipe** [comment]
![image](https://user-images.githubusercontent.com/11898833/117217992-3fdfe880-adfa-11eb-810c-99c9a6471196.png)


Seems to be all right for me, no matter what browser, browser size, device or zoom setting I use, it seems to work.

This has either already been fixed or it's an specific environment issue, possibly with fonts?

**Comment by spikecodes** [comment]
I was able to reproduce this as well but I don't see how this offset can be solved. Increasing the top padding (which lowers the upvote score down) one pixel now makes the upvote score slightly too low relative to the comment count.

![image](https://user-images.githubusercontent.com/19519553/126057527-9cc8fd63-4c23-4725-9b48-5711d64d1076.png)

**Comment by spikecodes** [comment]
Since this issue was opened and since curlpipe's screenshot, Libreddit has switched to Inter as the default font which appears to have slightly affected this offset issue.

**Comment by spikecodes** [comment]
The issue no longer seems apparent with Inter as the font.
