### ISSUE TITLE
Make "Awards visible" optional

### ISSUE THREAD

**Issue by lbrdt** [libreddit/libreddit#442]
## Is your feature request related to a problem? Please describe.

The Awards are not essential to the discussion and take extra requests.

## Describe the solution you'd like

Optional setting to make awards visible on the interface with it being off by default. On both posts and comments

### Screenshot of requests on `r/popular`
![Screen](https://i.imgur.com/iEPiybm.png)

annoying little critters

**Comment by maplepy** [comment]
especially with posts like these

https://libredd.it/r/Superstonk/comments/teezts/ryan_cohen_on_twitter/

**Comment by azizLIGHT** [comment]
A workaround for this issue, for anyone who wants it:

Using your favorite adblocker -> Options -> My filters, add these rules:
```
libredd.it/preview/pre/award_images/*
libredd.it/static/gold/awards/icon/*
libredd.it##.award
libredd.it##.awards
```
The first two rules block the requests from going through and the last two rules hide the broken icons. Replace libredd.it with your favorite instance as needed.

**Comment by kartikynwa** [comment]
Would appreciate this as well.

**Comment by DiegoMagdaleno** [comment]
Hi! I am the dev that implemented awards, are you still interested in this feature? I can try to maybe implement something!
