### ISSUE TITLE
Feature idea: SFW-only instances

### ISSUE THREAD

**Issue by rc2dev** [libreddit/libreddit#465]
First of all, thanks for Libreddit!

## Is your feature request related to a problem? Please describe.

If you want to make a network SFW, there isn't a way to block Reddit's NSFW content at DNS level. The administrator either has to go to more involved solutions such as a proxy, or block the entire website. [Here](https://libredd.it/r/ideasfortheadmins/comments/5jrz1x/i_am_a_sysadmin_for_schools_i_dont_want_to_block/) - [some](https://libredd.it/r/pihole/comments/p2g3k4/i_need_to_block_specific_subreddits_internetwide/) - [examples](https://libredd.it/r/HomeNetworking/comments/myqas1/blocking_nsfw_subreddits_with_opendns/).

## Describe the solution you'd like

Libreddit could have an environmental variable on the backend to allow/disallow serving NSFW content. If disabled, NSFW content would be filtered out at the backend and the toggle on the settings page would be missing. 

This way, there would be SFW-only Libreddit instances, besides the current NSFW-allowed ones. If wanted, the same domain could serve both versions on different subdomains.

The network administrator could then proceed to block reddit.com as well as Libreddit's NSFW instances. The users could access Reddit content normally through Libreddit SFW instances.

## Describe alternatives you've considered

None.

## Additional context

None.

Best regards!

**Comment by walkxcode** [comment]
Sir. 
![image](https://user-images.githubusercontent.com/71191962/163246715-f1e4411f-5d11-4c82-aaea-de13897bb0a4.png)

**Comment by rc2dev** [comment]
Have you read the documentation?

> Assign a default value for each setting by passing environment variables to Libreddit in the format LIBREDDIT_DEFAULT_{X}

That option just defines if NSFW content is shown or not _by default_. The user can still toggle it on settings page.

**Comment by walkxcode** [comment]
Block the settings page 🙃

**Comment by rc2dev** [comment]
Bye, troll.

**Comment by walkxcode** [comment]
I'm not trolling. Just giving you a temporary solution.

**Comment by rc2dev** [comment]
Ok, my apologies.

I actually already did something similar, which was hosting my own Libreddit instance with the "show NSFW" toggle removed and then blocking all other instances, as well as Reddit.

But this, as you said, is still a patch and far from ideal. For example:

- A competent user can create the NSFW toggle ad-hoc.
- Direct links for media, as far as I remember, still work.

Your solution of blocking the settings page is impossible via DNS and blocks access for the user for all settings, so also far from ideal.

The ideal is to patch the code in the backend so even a competent user can't fetch NSFW content from a particular instance, and no other functionality is lost.

**Comment by sphars** [comment]
Looks like this issue can be closed, as it's now implemented with #656. Thanks @Daniel-Valentine and team

**Comment by sigaloid** [comment]
Thanks!
