### ISSUE TITLE
💡 Feature request: Better way to view deleted comments

### ISSUE THREAD

**Issue by CubeyTheCube** [libreddit/libreddit#532]
## Is your feature request related to a problem? Please describe.
Currently when there are deleted comments, libreddit replaces the comments with links to [reveddit](https://reveddit.com), which has an archive of the comments. However, reveddit is extremely slow, and its UI is buggy and confusing. Also, it doesn't archive user-deleted comments.

## Describe the feature you would like to be implemented
Use [Pushshift's](https://pushshift.io) API (which reveddit is based off of) to show deleted comments when the "view removed comment" is clicked.
- This may not be an ideal solution, since this would require JavaScript
- An alternative is to retrieve all of the deleted comments server-side if there are any, but it's possible that it could be slow

## Describe alternatives you've considered
Linking to [Unddit](https://www.unddit.com/) rather than reveddit, since it's much faster.

**Comment by spikecodes** [comment]
Added in [v0.23.1](https://github.com/libreddit/libreddit/releases/tag/v0.23.1)
