### ISSUE TITLE
🐛 Bug Report: Submission button on user pages is cutoff

### ISSUE THREAD

**Issue by guaddy** [libreddit/libreddit#548]
## Describe the bug
Specifically on mobile devices, when viewing a user page, the **Submitted** button and text is cut off, making it somewhat difficult to select. (Only confirmed on iPhone 12 Pro Max using Safari)

## Steps to reproduce the bug

1. Go to any user page (Use https://libredd.it/user/spez for example)

## What's the expected behavior?
Overview, Comments, and Submitted ideally would all be equally shown. Another idea would be to make these buttons scrollable if they are being cut off. 

## Additional context / screenshot

![BD4A0056-A73F-4F6A-8E29-5E08DCE06A32](https://user-images.githubusercontent.com/67671414/178125251-4f61df93-7387-4488-b53d-c6624bf846d9.jpeg)

**Comment by ranmerc** [comment]
We can do a `overflow-x: auto` at [line 489 of /static/style.css](https://github.com/spikecodes/libreddit/blob/57d304161b3af6bee4ff849f39d80e7a6d020510/static/style.css#L489)

I have checked and it does not produce any visual errors for other elements in the selector but still we could add a separate rule for `#listing_options` containing only `overflow-x: auto`

Should I make a pull request?

**Comment by spikecodes** [comment]
Thanks for the suggestion @ranmerc, I did exactly that.
