### ISSUE TITLE
How to debug ARM image?

### ISSUE THREAD

**Issue by FarisZR** [libreddit/libreddit#555]
Hello, first thanks for the Awesome Project!

I have Libredditt hosted, and its timing out, and I couldn't locate the problem.

The Readme says to build the image local without `--release`, but the Arm dockerfile doesn't include it anyway.

So what's the best way to debug Libreddit?, it would be better if you could include an environment variable to enable debugging mode.

**Comment by spikecodes** [comment]
Hey @FarisZR :wave: 

I recommend cloning the codebase and using `cargo run` (without --release) to debug Libreddit. This will allow you to edit the code and then rerun it (with the same command) to test different ideas. It will allow provide you with the IDs of requested posts on your local instance.

Hope this helps. If you need further assistance, please let me know.
