### ISSUE TITLE
💡 Feature request: utils.rewrite_urls should support all domains, including preview

### ISSUE THREAD

**Issue by austinhuang0131** [libreddit/libreddit#559]
## Is your feature request related to a problem? Please describe.
Some posts contain preview URLs within a post which Libreddit does not correctly proxy.

## Describe the feature you would like to be implemented
`utils.rewrite_urls` should support all domains as specified in `utils.format_url`.

## Describe alternatives you've considered
Using a redirector addon...

**Comment by mikupls** [comment]
I think I ran into this today.

My fix was in `src/utils.rs`:
```
-static REDDIT_PREVIEW_REGEX: Lazy<Regex> = Lazy::new(|| Regex::new(r"https://external-preview\.redd\.it(.*)[^?]").unwrap());
+static REDDIT_PREVIEW_REGEX: Lazy<Regex> = Lazy::new(|| Regex::new(r"https://(external-preview|preview)\.redd\.it(.*)[^?]").unwrap());
```

If this repo becomes active again, happy  to send a PR.
