### ISSUE TITLE
✨ Feature parity: Subscriptions saved across devices/browsers (self hosted instance only)

### ISSUE THREAD

**Issue by ozzeruk** [libreddit/libreddit#560]
## How does this feature work on Reddit?

I can log into Reddit from any browser or device and it 'has remembered' which subreddits I read (all 200 odd of them).

## Describe how this could be implemented into Libreddit

Currently, Libreddit uses cookies to save which subreddits are subscribed to. I self-host Libreddit, and the same information could be in a simple text file inside the Docker container where I'm running Libreddit.

## Describe alternatives you've considered

One alternative is to subscribe to each new subreddit I discover and want to follow on each device I use. This isn't ideal and with 3 computers and a couple of mobile devices it isn't practical.

## Additional context / screenshot

I appreciate this feature doesn't make sense on a public Libreddit instance.
However, this feature makes complete sense on a privately self-hosted Libreddit instance.
I believe this feature should be very straightforward to implement as effectively we're just pointing Libreddit to a cookie text file inside the docker container rather than one held by the browser.
Without the feature, if I move to a different computer and view my private Libreddit instance, I lose everything and have to resubscribe to everything.

**Comment by xrfmkrh** [comment]
you can already use this feature with environment variable.
like this `LIBREDDIT_DEFAULT_SUBSCRIPTIONS=askreddit+selfhosted`

**Comment by u175** [comment]
Hi, is there an environment variable for subscribing to users?

**Comment by spikecodes** [comment]
Hi @ozzeruk, as shared by @xrfmkrh and @nemesio65 [here](https://github.com/libreddit/libreddit/issues/359#issuecomment-989179035), this is possible with the `LIBREDDIT_DEFAULT_SUBSCRIPTIONS` environment variable. Only downside is you have to change the env var to change your subscriptions (the default seems to override what you subscribe to in the web interface).

@u175 Yes, a subscription to `u/urfaselol` is the same as subscribing to `r/u_urfaselol` so simply prepend `u_` to your user subscriptions in the environment variable:
```bash
LIBREDDIT_DEFAULT_SUBSCRIPTIONS=askreddit+selfhosted+u_urfaselol
```
