### ISSUE TITLE
✨ Feature parity: Sound for Redgifs posts

### ISSUE THREAD

**Issue by tuxayo** [libreddit/libreddit#564]
## How does this feature work on Reddit?
There is a Redgifs iframe it's muted by default. And when unmuting, the sound works.

## Describe how this could be implemented into Libreddit
No iframe (for privacy) like now but have the video with sound.

## Describe alternatives you've considered
Spinning up TOR browser and going to reddit, get the Redgifs link and go there. But it's so slow and uses TOR resources when it could be avoided.

## Additional context / screenshot
Example: The post itself is totally SFW, but the sureddit logo isn't and the other posts bellow the page aren't.
https://www.reddit.com/r/NsfwAccumulator/comments/vppyfi/vibrator_with_sound_control_vs_technical_problems/

**Comment by spikecodes** [comment]
Hi, this seems to be the same issue as reported in #575 but for a different GIF service so I'll merge this into that one and make that issue more generally about a lack of sound for embedded GIFs.
