### ISSUE TITLE
✨ Feature parity: Display the Redgifs link for Redgifs posts

### ISSUE THREAD

**Issue by tuxayo** [libreddit/libreddit#565]
## How does this feature work on Reddit?
Bellow the post title there is a small link to go directly to the Redgifs page.

## Describe how this could be implemented into Libreddit
Show a small link to go directly to the Redgifs page.

## Additional context / screenshot
Example: The post itself is totally SFW, but the sureddit logo isn't and the other posts bellow the page aren't.
https://www.reddit.com/r/NsfwAccumulator/comments/vppyfi/vibrator_with_sound_control_vs_technical_problems/

**Comment by spikecodes** [comment]
Thanks for this suggestion! Merging this into #577
