### ISSUE TITLE
🐛 Bug Report:  "Open in Reddit button" too close to Settings button (especially in mobile UI)

### ISSUE THREAD

**Issue by opusforlife2** [libreddit/libreddit#596]
## Describe the bug

The button to open the page in Reddit proper is far too easy to tap/click on accidentally. For a user who is interested in protecting their privacy from Reddit, this is quite troubling.

## What's the expected behavior?

The button should be positioned separately from other buttons. If possible, there should be a confirmation dialogue stating that the user is leaving the Libreddit instance and opening Reddit, like how many forum websites warn users about external links.

**Comment by spikecodes** [comment]
Fixed in #643
