### ISSUE TITLE
💡 Feature request: subreddit post sort: old

### ISSUE THREAD

**Issue by lokyinng** [libreddit/libreddit#597]
## Is your feature request related to a problem? Please describe.
 nope

## Describe the feature you would like to be implemented
add subreddit post sort: old

## Describe alternatives you've considered
 also nope

**Comment by spikecodes** [comment]
I agree with Daniel. The Reddit sort methods don't include an `old` one currently for subreddits and it would be very difficult from Libreddit's end to implement our own so this feature is not planned.
