### ISSUE TITLE
PSA: Ferrit v0.1.0, a fork of Libreddit, released

### ISSUE THREAD

**Issue by Daniel-Valentine** [libreddit/libreddit#599]
I've released [Ferrit v0.1.0](https://github.com/ferritreader/ferrit/releases/tag/v0.1.0) today. [Ferrit](https://github.com/ferritreader/ferrit), previously _libbacon_ (see #594), is a fork of Libreddit to build on @spikecodes et al.'s excellent work, address [outstanding Libreddit issues](https://github.com/spikecodes/libreddit/issues), and keep the project alive. Ferrit v0.1.0 already includes code to address open issues/PRs in this project:

* #482
* #508
* #574
* #592

If you are hosting a Libreddit instance, I highly encourage you to switch over to Ferrit, which is actively maintained, whereas Libreddit is not. The Ferrit GitHub org also maintains a [separate repo, ferritreader/ferrit-instances](https://github.com/ferritreader/ferrit-instances), that hosts a hopefully up-to-date list of active Ferrit instances. Should you switch to Ferrit, you are more than welcome to open a PR in that to add your instance.

We have [a separate Matrix room](https://matrix.to/#/#ferrit:matrix.org) for Ferrit, although I am also active in the [Libreddit room](https://matrix.to/#/#libreddit:kde.org) as well; see the [_Discuss_](https://github.com/ferritreader/ferrit/wiki/Discuss) Ferrit wiki page.

@spikecodes: Once again, thank you for building Libreddit. Please let us know when you are back, and if we should synchronize Ferrit with Libreddit.

**Comment by spikecodes** [comment]
Hi all! I apologize for my absence but I am back.

There is clearly a lot of people who still use Libreddit so I will do my best to keep the project alive and am grateful for your efforts to do so. @Daniel-Valentine 

1. Are those four pull requests/issues the only things currently separating Ferrit from Libreddit? I would happily support synchronizing the new projects (into this repo as it has most of the contributions currently).
2. To prevent my absences from stalling the project's growth in the future, I'm launching the @libreddit organization and will transition Libreddit there to become a community-maintained project. @Daniel-Valentine If you're interested, I'd love for you to become a project manager. Feel free to message me on Matrix about this further.

**Comment by eUgEntOptIc44** [comment]
Hi @spikecodes great to have you back! 👍

**Comment by Daniel-Valentine** [comment]
@spikecodes: Great to have you back, and as I've said before, thank you so much for your hard work on Libreddit. Answering your questions in reverse order:

> To prevent my absences from stalling the project's growth in the future, I'm launching the https://github.com/libreddit organization and will transition Libreddit there to become a community-maintained project. @Daniel-Valentine If you're interested, I'd love for you to become a project manager. Feel free to message me on Matrix about this further.

I would be more than happy to take on this role, and I'd like to put in a good word for @sigaloid, who had also made numerous contributions to the Ferrit codebase since its start. I agree that we should merge the two projects together. Here is what I think we should do:

1. Begin the process of porting Ferrit changes into Libreddit. This will require some ugly diffing, but I'll be more than happy to assist with this.
2. Come up with a new name for Libreddit. We have to do this, unfortunately, because of the [probable Reddit API TOS violation](https://github.com/libreddit/libreddit/issues/585#issuecomment-1251685606). This is where I'd like community input. Admittedly, I'm biased toward "Ferrit" simply because I think the name is cute, which is partly why I think we should have the public decide on this, precisely _because_ of my bias.
3. Port issues in [ferritreader/ferrit](https://github.com/ferritreader/ferrit) to this project.
4. Terminate the Ferrit fork as it no longer serves its purpose.

Re (2), I think we should do this in a poll either here in GitHub or on Matrix. GitHub would provide more visibility, but Matrix has a lower barrier to entry (there are people who will not sign up for GitHub).

> Are those four pull requests/issues the only things currently separating Ferrit from Libreddit? I would happily support synchronizing the new projects (into this repo as it has most of the contributions currently).

These were just the fixes that have made it into 0.1.0. Those issues have corresponding PRs:

* ferritreader/ferrit#14 (c/o @NKIPSC)
* ferritreader/ferrit#9
* ferritreader/ferrit#22
* ferritreader/libreddit-fork#11

 Some of the other substantial fixes that made it into 0.1.0 I neglected to include are:

* ferritreader/libreddit-fork#10 (@spikecodes addressed this in 170ea38)
* ferritreader/ferrit#24
* ferritreader/ferrit#25
* ferritreader/ferrit#28

Since that release, there have been new additions to the code base:

* ferritreader/ferrit#46 (@spikecodes has addressed this in b170a8d)
* ferritreader/ferrit#54
* ferritreader/ferrit#58
* ferritreader/ferrit#59

There are a few other fixes that I committed directly into master. Bad form on my part, I know, and I would have to look through the commit history to account for those changes. Most major revisions to code, however, went through the PR process, and were co-reviewed by me and @sigaloid.

**Comment by spikecodes** [comment]
Thank you for the detailed write-up of Ferrit's distinctive features to be moved into Libreddit. This will serve as a useful checklist in re-streamlining the development of the project. I'm moving this issue to a discussion where it can be easily referred back to as we synchronize the two projects.

I am totally fine with @sigaloid being added to the Libreddit organization, he seems like a valuable contributor.
