### ISSUE TITLE
🐛 Bug Report: Links can be seen in spoiler tags

### ISSUE THREAD

**Issue by SuperSamus** [libreddit/libreddit#610]
## Describe the bug

Spoilers are supposed to be invisible until you put the cursor over them. However, if there's a link in the spoiler, it will be visible anyway.

## Steps to reproduce the bug

1. Go to a post/comment (tested only on a comment) with spoiler that has a link in it
2. You can clearly see the link

## What's the expected behavior?

The link should be hidden along with the spoiler.

## Additional context / screenshot

Reddit screenshot:

![image](https://user-images.githubusercontent.com/40663462/199843786-9d36742e-2a20-44d0-8c62-45eb3ca5f1cb.png)

Libreddit screenshot:

![image](https://user-images.githubusercontent.com/40663462/199843901-474642db-e8b2-42d0-8695-25fbe59339a4.png)

**Comment by spikecodes** [comment]
Thanks for reporting this! Can you send a link to a spoilered comment containing a link to help us debug this?

**Comment by SuperSamus** [comment]
https://libreddit.spike.codes/r/Games/comments/yl6np4/sonic_frontiers_showdown_trailer/iuxjua7/?context=3

**Comment by Scoder12** [comment]
Seems that link styling has a higher priority: 
![link styling and spoiler styling in devtools](https://user-images.githubusercontent.com/34356756/199886683-4abec9ea-a429-49c9-99f5-b1526b704295.png)

**Comment by Scoder12** [comment]
One fix is to add `> *` to the end of `.md .md-spoiler-text`, not sure if that would work with hover

**Comment by spikecodes** [comment]
Thanks for the help @Scoder12
