### ISSUE TITLE
💡 Feature request: Add a "hosted by" indication somewhere.

### ISSUE THREAD

**Issue by Midou36O** [libreddit/libreddit#621]
## Is your feature request related to a problem? Please describe.
This is just a completion over what have been suggested previously in libreddit/ferrit#49 (last comment).

## Describe the feature you would like to be implemented
A "hosted by" or an indication of where this instance is being hosted, preferably in the footer (future proofing considering the top bar is starting to get clogged up. See https://github.com/ferritreader/ferrit/pull/48#issuecomment-1287548866 ).

## Describe alternatives you've considered
n/a

## Additional context / screenshot
n/a

**Comment by spikecodes** [comment]
Could either be displayed in a banner (#347) or info page (#624) so closing this issue in favor of those
