### ISSUE TITLE
🐛 Bug Report: Default card display is broken on Firefox Android

### ISSUE THREAD

**Issue by lbrdt** [libreddit/libreddit#622]
## Describe the bug
The theme's image content are not well displayed like they were in libreddit.  Text are also overflowing on posts

## Steps to reproduce the bug

1. Download Firefox Android
2. Go to a ferrit instance

## What's the expected behavior?
It should look the same as in mobile chromium variants

## Additional context / screenshot
https://user-images.githubusercontent.com/87078313/198188751-2183b863-6de4-48fc-9bf4-4b2b14ae2bb9.png

https://user-images.githubusercontent.com/87078313/198189211-b9de0154-1c2d-4eb5-8af6-919958a882a8.png

**Comment by lokyinng** [comment]
it does apply to mobile version of Google

**Comment by chloekek** [comment]
Same issue on Linux Firefox desktop. Ctrl+Shift+R fixed it.

Perhaps a future-proof fix would be to include the version number of the software in the query string of the URL stylesheet.

**Comment by Daniel-Valentine** [comment]
Resolved in the commit given above, using the fix offered by @chloekek above.
