### ISSUE TITLE
Detail instance info in a REST endpoint or existing page metadata

### ISSUE THREAD

**Issue by Daniel-Valentine** [libreddit/libreddit#624]
Add data in the `<head>` block that details information about the Libreddit instance. Example, using [`<meta name="application-name">`](https://html.spec.whatwg.org/multipage/semantics.html#meta-application-name):

```jinja2
<meta name="application-name"
    content="Libreddit"
    data-version="{{ env!("CARGO_PKG_VERSION") }}"
    data-hls-enabled="false"
    data-default-theme="dark"
    data-sfw="true"
    data-sfw-only="false"
    data-content-encoding="gzip"
/>
```

This is not the only way we could add info to `<head>`. Per [this Stack Exchange post](https://stackoverflow.com/a/19298638), we have other options, including defining a `<script type="text/plain">` block with content of our own encoding (e.g. CSV). That might even be preferable to a `<meta>` tag.

The purpose for this is so that instance scrapers, like [libreddit/libreddit-instances](https://github.com/libreddit/libreddit-instances), can get information about them without having to rely on hard-coded data, e.g. the CSV in the libreddit-instances repo. This would help address libredirect/libredirect#477.

**Comment by throwaway-d** [comment]
The icon is so ugly and the location looks eyesore.  I think it should be placed on the left of the header next to `libreddit. v0.29.3`
![image](https://user-images.githubusercontent.com/121148372/219906616-624f7f9f-0c23-4f24-835e-a891cc0bdb62.png)

**Comment by spikecodes** [comment]
I think the icon is fine but I agree that it is too prominent. I'll be addressing this in a PR that responds to #716 so check that issue for updates on this.
