### ISSUE TITLE
Container image

### ISSUE THREAD

**Issue by artemislena** [libreddit/libreddit#630]
L: We could start hosting libbacon (we wanted to host Libreddit again alongside Teddit, which we switched to after uh, the maintenance situation there became unclear), but we'd need a container (i.e. Docker) image for that, and couldn't find one on Quay or Docker Hub yet. https://github.com/libbacon/libbacon/issues/2 would also be relevant here, I mean, you would probably like to put that in the documentation, too. Ideally, you could build this via CI ‒ we don't know too much about GH Actions, or any CI really, but I think it's not too hard to make it build things and push them on, say, Quay, or GHCR, or using another CI for that, or perhaps just your own build machine.

**Comment by Daniel-Valentine** [comment]
With the resumption of the Libreddit project I've transferred this over to the Libreddit issue tracker. @spikecodes has applied for the Docker open source program and we hope to hear back from them soon.

**Comment by fr3fou** [comment]
Would it be possible to have some tags on the Docker images themselves with versions? https://hub.docker.com/r/spikecodes/libreddit/tags There's only `latest` and the `arm`/`armv7` but no tags such as `v0.24.1`

**Comment by spikecodes** [comment]
That's a good idea @fr3fou, I've opened https://github.com/libreddit/libreddit/issues/655 to address this.
