### ISSUE TITLE
🐛 Bug Report: Docker Hub does not have the latest build

### ISSUE THREAD

**Issue by ShakeyBones3** [libreddit/libreddit#680]
## Describe the bug

The image hosted on Docker Hub is not the latest and is currently at v0.25.0.

## Steps to reproduce the bug

1. Go to `https://hub.docker.com/r/spikecodes/libreddit/tags` or `docker pull spikecodes/libreddit:latest`

## What's the expected behavior?

The latest version is available on Docker Hub.

**Comment by spikecodes** [comment]
Hi! I'm not sure if you saw in the README but we've moved to a Docker organization so the new URL is `https://hub.docker.com/r/libreddit/libreddit` and the new address is thus `libreddit/libreddit` not `spikecodes/libreddit`.
