### ISSUE TITLE
💡 Feature request: Add option for Pushshift API site

### ISSUE THREAD

**Issue by r7l** [libreddit/libreddit#682]
Last year it was requested to switch from reveddit.com to unddit.com as it was considered slow. While that was the case back then, it's the opposite now. Unddit isn't working well recently. Since both of them are interchangeable by just using the other domain it would be great to have an option like `LIBREDDIT_PUSHSHIFT_FRONTEND` where you can set the domain.

**Comment by sigaloid** [comment]
Hi, I've got a patch for this but I'll wait for #685 to go in to avoid a merge conflict.

**Comment by sigaloid** [comment]
Fixed by #812
