### ISSUE TITLE
LIBREDDIT_DEFAULT_SUBSCRIPTIONS setting is no longer read

### ISSUE THREAD

**Issue by lleddewk** [libreddit/libreddit#689]
Since upgrading to v0.27.0, the $LIBREDDIT_DEFAULT_SUBSCRIPTIONS setting is not honoured as it was in previous versions. The result is that I see the a feed of random posts rather than the feeds that I am interested in. I think this was caused by the changes introduced by pull request #664.

Thanks
Keith

**Comment by sigaloid** [comment]
This configuration was undocumented so I didn't know to include it in my PR. I'm going to fix this right after #685 goes in to avoid a conflict.

**Comment by lleddewk** [comment]
Yeah I  realised that after posting so not surprising you didn't pick it up.  Grateful for the fix in due course.

Thanks
Keith

**Comment by r7l** [comment]
Thanks allot for your work. Sadly it seems as if it didn't make it into the 0.27.1 release. Would be great to see it fixed at some point. For the time being i'm forced to stick with 0.26 as i don't want to loose this setting.

**Comment by sigaloid** [comment]
Apologies, I was hoping we could get #685 in before 0.27.1 - I'm going to add it as soon as it goes in so we can get it for the next release which should be soon as we've been working through the PR. It's a sizable change so we want to make sure it is done right.

**Comment by lleddewk** [comment]
Appreciate the efforts. As a workaround, you can save a bookmark to https://your.libreddit.site/r/sub1+sub2+sub3/.

Keith

**Comment by r7l** [comment]
Great to see that blocking PR made it into the new release.

**Comment by sigaloid** [comment]
Hi, apologies for the stagnation. I was planning on having this go right after 685 but we've cut a new release. 

I'm working on this right now!
