### ISSUE TITLE
✨ Feature parity: OP's username in blue

### ISSUE THREAD

**Issue by rndmh3ro** [libreddit/libreddit#693]
## How does this feature work on Reddit?

In a reddit thread when the OP posts a message, their name is blue and has a microphone emoji next to it (to distinguish the OP from other users). 

## Describe how this could be implemented into Libreddit
Probably with css. :) 

## Additional context / screenshot

![Screenshot_20230108-152409_1](https://user-images.githubusercontent.com/3198961/211201628-80c0668d-788e-4916-80c9-5afb2157d429.png)

**Comment by sigaloid** [comment]
This might be a problem with custom themes, we can't really override the css because it might not look right. Perhaps we add a new field to the theme for "OP color".

**Comment by r7l** [comment]
Why does it need to blue? OP users are already marked with bold and colored name.

**Comment by rndmh3ro** [comment]
You're right and I noticed that now, too. My bad.

It's actually fine the way it is.
