### ISSUE TITLE
✨ Feature parity: Allow viewing of gated subreddits

### ISSUE THREAD

**Issue by rioting1312** [libreddit/libreddit#697]
## How does this feature work on Reddit?
Usually, you agree to view a gated subreddit, and then you can view it. On libreddit, it just says, "gated", and you can't proceed further to view the content.

## Describe how this could be implemented into Libreddit
Allow the server hosting a libreddit instance to access the gated content, and then serve it to the viewers accessing the instance after displaying the gate's specific content, if the viewer agrees to the gate.

## Describe alternatives you've considered
Well, there currently isn't one, for people who want to use libreddit to view gated subreddits...

**Comment by sigaloid** [comment]
Hi, I'm not sure what you mean by "gated". Can you provide an example of a gated subreddit?

**Comment by rioting1312** [comment]
all the drug-related subreddits were recently "gated". This functionally broke libreddit from proxying these pages. You can see why users might want to use libreddit for these type of pages; they are more likely to value their privacy, and be suspicious of reddit's intention of surveilling them.

https://www.reddit.com/r/drugs


Jan 17, 2023, 06:17 by ***@***.***:

**Comment by sigaloid** [comment]
Ah, okay. Thanks for the report. I'm going to investigate later - I don't think it's going to require a special bypass, like an account cookie from the server operator. On old.reddit.com it's available just by pressing view (same as NSFW) but I guess the JSON route requires some parameter or header not already set.

**Comment by Daniel-Valentine** [comment]
The `gated` message, laconic as it is, comes directly from Reddit via their JSON API. The same holds true for `banned` (and other strings I can't remember). What we can do for now is change this message to something more explicit, like

> Reddit has gated this content and made it unavailable for viewing.

Same thing for `banned`

> This post cannot be viewed because it is on a subreddit that is banned.

(or perhaps just use the same message that appears when trying to access a banned subreddit: "r/[sub] has been banned from Reddit")

**Comment by Daniel-Valentine** [comment]
We do need to be mindful of the [Reddit API TOS](https://archive.ph/qYYrT), specifically 3(b)(iii):

> 3.  Fees; Restrictions on Use. 
>     b.  Restrictions.  You must not, and must not allow those acting on your behalf to:
>     	iii.    circumvent or exceed limitations on calls and use of the Reddit APIs as outlined in the API Documentation, or otherwise use the Reddit APIs in a manner that would constitute excessive or abusive usage or would disrupt or unreasonably interfere with the Reddit APIs or the servers or networks that provide the Reddit APIs.  If Reddit believes that you are in breach of this section, Reddit reserves the right to permanently block your access to the Reddit APIs.

If Reddit's JSON API does not offer a way to view gated content, then, unfortunately, there's nothing we can do within the bounds of the API agreement.

**Comment by sigaloid** [comment]
I'm pretty sure we can bypass this and display the content (gated perhaps as `Quarantined`) without breaking the API agreement, teddit looks to be able to view it solely via the API.

**Comment by rioting1312** [comment]
"I'm pretty sure we can bypass this and display the content (gated perhaps as Quarantined) without breaking the API agreement, teddit looks to be able to view it solely via the API."

That is great news. Otherwise, libreddit's functionality for ALL subreddits targeted with gating, will be broken. Drug users and people discussing this matter, are people who are uniquely vulnerable to corporate censorship and surveillance; if possible, I think it a great idea to bypass the gates.

additionally, it will also be helpful to broadcast the message in the gate, which provides the SAMHSA addiction treatment help line. So, it is in the best public interest to both render the gate's content fully, and allow users to access the subreddit content if they want to, as well.


Jan 17, 2023, 18:38 by ***@***.***:

**Comment by sigaloid** [comment]
`curl 'https://old.reddit.com/r/meth.json' -H 'Cookie: _options=%7B%22pref_gated_sr_optin%22%3A%20true%7D'`

@Daniel-Valentine, can you speak on whether this breaks the Terms of Service? https://libreddit.spike.codes/r/redditdev/comments/tjl1c8/bug_gated_subreddits_inaccessible_via_oauth/

**Comment by spikecodes** [comment]
@rioting1312 Thanks for opening this issue! This would be a good feature to support, just as we currently support Quarantined and NSFW walls for those subreddits.

I don't believe that passing the cookie to access the gate (after prompting the user with the same message that Reddit passes, and waiting for them to click "continue") would violate their Terms of Service any more than existing Libreddit pages would. We'd simply be re-implementing the same gate interface that Reddit.com uses, just as we've re-implemented other Reddit pages.

On the technical side: We could probably merge [`nsfwlanding.html`](https://github.com/libreddit/libreddit/blob/master/templates/nsfwlanding.html) and [`wall.html`](https://github.com/libreddit/libreddit/blob/master/templates/wall.html) to create `gate.html` which could serve as the "Are you sure you want to continue?" page for quarantined, NSFW, and gated content.
