### ISSUE TITLE
🐛 Bug Report: autoplay_videos missing from restore preferences link.

### ISSUE THREAD

**Issue by The1029** [libreddit/libreddit#699]
## Describe the bug
The autoplay_videos preference is missing from the generated restore preferences link.

## Steps to reproduce the bug
Click/paste the restore preferences link.

## What's the expected behavior?
The autoplay_videos preference should be present.

**Comment by spikecodes** [comment]
Thanks for catching this! Should be fixed once [v0.27.2](https://github.com/libreddit/libreddit/releases/tag/v0.27.2) is out.
