### ISSUE TITLE
🐛 Bug Report: Enabling "Do not confirm before visiting content on Reddit" only leaves "reddit.com" navbar link

### ISSUE THREAD

**Issue by lbrdt** [libreddit/libreddit#713]
## Describe the bug

Enabling "Do not confirm before visiting content on Reddit" only leaves "reddit.com" navbar link, not the whole reddit post link

## Steps to reproduce the bug

1. Turn on the "Do not confirm before visiting content on Reddit" on settings.
2. Go to a post
3. Tap on the reddit icon on the top bar
4. It only links to "reddit.com"

## What's the expected behavior?

A link to the post on reddit

**Comment by Daniel-Valentine** [comment]
Fixed in the latest release (v0.29.1). My apologies.
