### ISSUE TITLE
Reduce the prominence of the instance info button

### ISSUE THREAD

**Issue by blackpill0w** [libreddit/libreddit#716]
## Describe the feature you would like to be implemented
Changing the appearance of the button.

## Describe alternatives you've considered
Maybe just text saying information/about in the very bottom or maybe add it to the top bar.

**Comment by mikupls** [comment]
Making the button less prominent (https://github.com/libreddit/libreddit/commit/37f71c48d1b1e4636e7a07bb6398f6829fa91de8) was a step in the right direction, and I also vote for going further. Instance information is not something a normal user cares about and it is currently very prominently displayed (especially in threads with few or no comments).

IMO the same goes for the "code" button on the top right.

I'd like to see both move to the bottom of the page (see e.g. the small links at the bottom of GitHub itself).
Or consider moving them both into the top bar (IMO the worse option). But at least use a consistent place for developer-focused information.
The libreddit version from the top left could also go there (the only reason to check it is for devs to see if you are on the latest version, right?)

If this idea is generally okay (moving dev info to the bottom), I'm happy to give it a try.
