### ISSUE TITLE
🐛 Bug Report: awards are displayed incorrectly on small screens

### ISSUE THREAD

**Issue by mikupls** [libreddit/libreddit#717]
## Describe the bug

![grafik](https://user-images.githubusercontent.com/93015331/218313538-58a06c2b-224c-498d-9140-6789432b4731.png)

Award display is buggy on small screen sizes (e.g. smartphone, or small desktop browser window).

## Steps to reproduce the bug

See above. I think the root cause is the following css that seems to be added once a small screen size is detected:

![grafik](https://user-images.githubusercontent.com/93015331/218313611-afd187fa-3fca-40ea-a5be-cb2fd135279b.png)

Manually removing that css seems to fix the problem:

![grafik](https://user-images.githubusercontent.com/93015331/218313654-f96b8b35-ba88-4fc3-afa4-749511d55e07.png)

I believe the bug was introduced recently, but have not done any debugging yet.

## What's the expected behavior?

Awards are displayed properly.

---

Browser is firefox v109.

PS: while making these screenshots, I also noticed that the alignment of the "% upvoted" is inconsistent between the views.

**Comment by Daniel-Valentine** [comment]
I'll take blame and responsibility for this. We've started seeing these issues in fa68bf5, which is my merge of the changes introduced #643. The code in @potatoesAreGod's branch worked fine, so the issues that we see here are the result of merge mistakes on my part.

**Comment by Daniel-Valentine** [comment]
Should be fixed in v0.29.3. Vielen Dank, dass Sie diesen Fehler gefunden haben!

**Comment by mikupls** [comment]
Thanks for the quick fix!

I can confirm that the three points mentioned in https://github.com/libreddit/libreddit/commit/35504eda140ac01c9cac3800fb4df27e78b354d9 seem to be fixed.

Took me a moment to find where I leaked my language preferences :)
