### ISSUE TITLE
🐛 Bug Report: Every instance is having issue

### ISSUE THREAD

**Issue by freedit-dev** [libreddit/libreddit#729]
https://github.com/libreddit/libreddit-instances/blob/master/instances.md

> Reddit is having issues, check if there's an outage
Head back [home](https://libreddit.strongthany.cc/)?

**Comment by johanhalse** [comment]
Interestingly, [teddit](https://teddit.net) is down too. Did reddit cut off access?

**Comment by delendum** [comment]
It seems to have just recovered - that was strange. Every single instance was down but the site was still accessible. All are back online now.

**Comment by sigaloid** [comment]
Parts of the API were down - the JSON route was having issues, specifically. If this happens, there's nothing Libreddit could do to recover. The Reddit site was probably up because of caching.

**Comment by spikecodes** [comment]
Yeah, it sounds like there was a Reddit API outage earlier today. Closing this
