### ISSUE TITLE
🐛 Bug Report: DISABLE_VISIT_REDDIT_CONFIRMATION does not seem to work

### ISSUE THREAD

**Issue by mikupls** [libreddit/libreddit#736]
## Describe the bug
configuring `LIBREDDIT_DEFAULT_DISABLE_VISIT_REDDIT_CONFIRMATION` does not seem to work.

## Steps to reproduce the bug

I set `LIBREDDIT_DEFAULT_DISABLE_VISIT_REDDIT_CONFIRMATION=on`. Opening a new private window of my libreddit instance comes with the option disabled anyway. 

![image](https://user-images.githubusercontent.com/93015331/222424631-d0aaea35-deb0-4f1e-a6fc-816103985921.png)

(note that the theme preference gets correctly applied)

However, manually setting the option in the WebUI sets the cookie "disable_visit_reddit_confirmation=on", after which the expected behaviour applies.

---

PS: It seems like options are generally a bit messy right now (e.g. https://github.com/libreddit/libreddit/pull/706). This new option (`DISABLE_VISIT_REDDIT_CONFIRMATION`) also does not seem to appear on https://github.com/libreddit/libreddit/blob/master/src/instance_info.rs#L156.
This is not intended as a complaint but rather suggesting that some refactoring is likely needed in order to avoid devs missing this (which is quite easy today).

**Comment by Daniel-Valentine** [comment]
Thanks for raising this issue and the PR.

In the background, I've been reworking how we handle configuration and will be opening a draft PR soon, hopefully this weekend. Our current process requires a lot of explicit references to config in code, which we can easily forget, which gives rise to situations like that which you've identified here. Hopefully, if my proposal's accepted, we won't see situations like these again.

**Comment by mikupls** [comment]
Thanks! Glad to hear you are looking into this :+1:
