### ISSUE TITLE
Specific user profiles giving 'unauthorized' error.

### ISSUE THREAD

**Issue by goryramsy** [libreddit/libreddit#743]
When I am browsing any libreddit instance, take for example libreddit.eu.org, which is version 0.29.1, specific users such as u/No_Inside_7580 report a 'forbidden' error. 

This error is reproducible across Firefox, and Chromium-based browsers without any addons or extensions. It is also reproducible in the [.spike.codes instance](https://libreddit.spike.codes/info), which is version [0.29.4](https://libreddit.spike.codes/info)

This is an image taken in a chromium based browser with Fedora Linux (sans wayland, if that helps).
![image](https://user-images.githubusercontent.com/95547467/223335585-2c99fd8a-ed5f-47fa-87ea-c80a2b2896a2.png)

Same result on a random macbook with google chrome, so it is **not** os/browser specific

I did try with a VPN, and was signed out for half of these tests.

**Comment by goryramsy** [comment]
Could this be [NetzDG](https://reddit.zendesk.com/hc/en-us/articles/360045289772-Germany-Network-Enforcement-Act-NetzDG-Reporting)?

**Comment by mikupls** [comment]
It looks like the user is simply banned:
![pic123](https://user-images.githubusercontent.com/93015331/223413063-a96cab31-7a32-4c52-882a-3b6513221f12.png)

In the future, a good first investigation step is checking the network log (in firefox, ctrl+shift+e for me).

There you can see (on reddit) that the request for this user's data comes back as a "403 forbidden", which means that libreddit cannot do anything in this case (except also show a forbidden page).

**Comment by goryramsy** [comment]
Thank you. It looks like, at least to me, that it was blocked with GTM on Reddit, probably because the account was malicious and they did not want it showing up in search results or the like.

https://www.redditmedia.com/gtm/jail?id=GTM-5XVNS82

Seems to be what was causing it. Looks like a Reddit thing, thanks for your answer, I'll mark this as closed.
