### ISSUE TITLE
🐛 Bug Report: Instance info footer covers bottom buttons (mobile)

### ISSUE THREAD

**Issue by sphars** [libreddit/libreddit#747]
## Describe the bug

The new footer introduced in v0.30.0 (via #728) partially covers the Next/Prev buttons at the bottom of subreddit pages. Appears to only be an issue in mobile portrait views

## Steps to reproduce the bug

Scroll to the bottom of page of any subreddit. Buttons are partially covered by footer.

## What's the expected behavior?

Buttons not covered

## Additional context / screenshot

Screenshot from mobile Firefox

![Screenshot_20230309-093323.png](https://user-images.githubusercontent.com/18315081/224092023-5efe869d-9663-4067-994a-050af3d3c05e.png)

**Comment by Daniel-Valentine** [comment]
Thanks for raising this bug. This has been fixed in the tip of master and the soon-to-be-released v0.30.1.
