### ISSUE TITLE
Footer creates horizonal scroll bar

### ISSUE THREAD

**Issue by wsy2220** [libreddit/libreddit#750]
## Describe the bug
Footer creates horizonal scroll bar

## Additional context / screenshot
The footer seems a little too wide. The scroll bar is gone if I remove the footer.

I'm on linux chrome 111.0.5563.64 

![2023-03-13-004028_2342x2007_scrot](https://user-images.githubusercontent.com/7259503/224558966-cb8f18f2-2440-41bf-af4e-a896d5924d64.png)

**Comment by invakid404** [comment]
I'm experiencing this as well on Vivaldi 5.7.2921.60. Manually removing the footer element through the devtools gets rid of the horizontal scrollbar for me too.

**Comment by MrRubberDucky** [comment]
Experiencing the same on Firefox 111.0.1, scroll bar goes away if footer gets removed.
