### ISSUE TITLE
🐛 Bug Report: PR_END_OF_FILE_ERROR

### ISSUE THREAD

**Issue by heredia21** [libreddit/libreddit#752]
Visiting https://libreddit.spike.codes I get the following error:

Secure Connection Failed

An error occurred during a connection to libreddit.spike.codes. PR_END_OF_FILE_ERROR

Error code: PR_END_OF_FILE_ERROR

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.

On Firefox/Brave.

**Comment by sigaloid** [comment]
Thank you for reporting this! We're currently dealing with an outage of the official server from @spikecodes - for now, [please use another instance](https://github.com/libreddit/libreddit-instances/blob/master/instances.md).

**Comment by spikecodes** [comment]
Hi, please see https://github.com/libreddit/libreddit/discussions/756
