### ISSUE TITLE
🐛 Bug Report: All instances show "Failed to parse page JSON data" upon opening any page

### ISSUE THREAD

**Issue by loma-baldsson** [libreddit/libreddit#754]
## Describe the bug
As of current, all libreddit instances documented on [libreddit/libreddit-instances](https://github.com/libreddit/
[libreddit-instances](https://github.com/libreddit/libreddit-instances)) running version v0.30.0 or v0.30.1 will not load any page, instead giving the error "Failed to parse page JSON data"

## Steps to reproduce the bug
1. Choose a libreddit instance and open it (e.g. [safereddit.com](https://safereddit.com/))
2. The link should display an error message that reads "Failed to parse page JSON data: expected value at line 2 column 1"

## Additional context / screenshot
Screenshot of [safereddit.com's home page](https://safereddit.com/)
![image](https://user-images.githubusercontent.com/102317848/225163652-bb8addef-844b-4fb2-a63d-123fdf96b795.png)

I'm assuming the devs already know about this, but I'm submitting an issue to track it.

**Comment by sigaloid** [comment]
This is related to the wider Reddit outage AFAIK - https://mashable.com/article/reddit-is-down-major-outage

**Comment by loma-baldsson** [comment]
Seems to be resolved - closing
