### ISSUE TITLE
Docker Hub

### ISSUE THREAD

**Issue by artemislena** [libreddit/libreddit#759]
L: Uhm, Docker Hub is apparently discontinuing its free tier: https://hacky.town/@rtyler/110023261891172425

Now, currently the official image is hosted on Docker Hub, and uhm, we don't know whether @spikecodes is using a free account for that. If you're using a paid account, alright, just close this issue, if not, maybe uh, you would like to move to quay.io, or GHCR or so? They still offer unlimited public repos for free.

**Comment by spikecodes** [comment]
Thanks, yeah we opened https://github.com/libreddit/libreddit/discussions/757 to address this.
