### ISSUE TITLE
🐛 Bug Report: "about to leave" all over page in broken state

### ISSUE THREAD

**Issue by lordkitsuna** [libreddit/libreddit#799]
## Describe the bug

I just updated to the latest version of libreddit and now the page is all broken with large "about to leave" all over the page (see attached image 
![image](https://user-images.githubusercontent.com/3444267/235836124-269a464f-907a-4d0b-9076-cf68bab96070.png)

## Steps to reproduce the bug

install latest using cargo build
open site
see error

## What's the expected behavior?

clean working page

if its helpful the problem can be viewed live at https://libreddit.kitsuna.net. i did not see this mentioned in the bug tracker so i assume its more likely a me issue but i am not sure why this would only now be an issue i have been hosting libreddit just fine for some time. i was rather out of date so it was a large jump in versions.

**Comment by mikewilzn** [comment]
Did you figure out the issue? I don't see it on your instance anymore. I'm having the same issue.

**Comment by mikewilzn** [comment]
Nevermind I had a reverse proxy setting wrong. Works fine after fixing that.

**Comment by lordkitsuna** [comment]
I forgot about this issue, it resolved itself after an update
