### ISSUE TITLE
What's Happening With The Official Instance???

### ISSUE THREAD

**Issue by Lanklow** [libreddit/libreddit#804]
I feel like I saw something here about the official instance being down temporarily, but I can't seem to find it.

Is there any info as to when it will be back?

**Comment by sigaloid** [comment]
Probably this: https://github.com/libreddit/libreddit/discussions/756

libreddit.spike.codes works currently, and you can check alternatives here: https://github.com/libreddit/libreddit-instances/blob/master/instances.md

**Comment by EJD799** [comment]
> libreddit.spike.codes works currently

No it doesn't:
![Screenshot 2023-06-01 7 03 53 AM](https://github.com/libreddit/libreddit/assets/108157991/fe419184-215d-427e-893c-1193bd3991ea)

**Comment by sigaloid** [comment]
It was up when I posted this :( 

In any case though, there are other instances available that are highly available - also, since Spike has stepped down from the project, I'm considering hosting an official instance myself.

**Comment by Lanklow** [comment]
I've been using Safereddit.com, but I was just curious what the status was. Also, Spike stepped down?!

Off-topic: With the news about the Reddit charging for API access; is libreddit able to continue operation?

**Comment by sigaloid** [comment]
> Also, Spike stepped down?!

Yep :(

> Off-topic: With the news about the Reddit charging for API access; is libreddit able to continue operation?

We're not sure yet - the changes haven't actually happened yet, and there's some technicalities (we use the anonymous `.json` endpoints, it's possible we could switch to the RSS feed if available, etc)... It's looking like we'll be impacted by these changes, though. There's more discussion in #785.

**Comment by Lanklow** [comment]
Alright, thanks for the update on everything.
