### ISSUE TITLE
🐛 Bug Report: Deploy fails on Replit

### ISSUE THREAD

**Issue by HashLiver** [libreddit/libreddit#809]
## Describe the bug

The console keeps looping this error: 
```
while :; do set -ex; curl -o./libreddit -fsSL -- https://github.com/libreddit/libreddit/releases/latest/download/libreddit ; chmod +x libreddit; set +e; ./libreddit -H 63115200; sleep 1; done
+ curl -o./libreddit -fsSL -- https://github.com/libreddit/libreddit/releases/latest/download/libreddit
+ chmod +x libreddit
+ set +e
+ ./libreddit -H 63115200
./libreddit: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./libreddit)
./libreddit: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./libreddit)
./libreddit: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./libreddit)
+ sleep 1
```

## Steps to reproduce the bug

Click the "Made with Repit" button, language select "Rust", then deploy fail.

## Additional context / screenshot

![drqTVzNhk0](https://github.com/libreddit/libreddit/assets/42889797/0ce671cb-588b-4e11-88d1-310a1db95a31)

**Comment by sigaloid** [comment]
Odd - the libc requirement of the binary doesn't match the repo, which is pretty common. I do wonder how this hasn't broken before.

I'll make a PR to add MUSL builds for the next release, if that works I'll update the `.replit` file and it should be fixed. :)

**Comment by sigaloid** [comment]
Merged, but I'm leaving this open as there's still work to do. Looks like static builds are working.

**Comment by Taratect** [comment]
Umm is this issue fixed? Because I cannot run Libreddit on replit. It gives me the error exit status 22.

I'm quite new at this. Idk if I'm doing anything wrong. I've successfully installed whoogle but libreddit isn't installing
