### ISSUE TITLE
🐛 Bug Report: Failed to parse page JSON data: expected value at line 1 column 1

### ISSUE THREAD

**Issue by np22-jpg** [libreddit/libreddit#869]
## Describe the bug
When attempting to use libreddit, I receive this error. Happens on both public instances as well as my private one. It began around now, 8:20 PM UTC. The (few) instances I could find have this error.

## Steps to reproduce the bug
1. Go to any libreddit instance (including your own self-hosted one)
2. Cry

## What's the expected behavior?

Libreddit does not error out.

**Comment by np22-jpg** [comment]
It seems intermittent, actually. Oh well.

**Comment by floptical** [comment]
Something funny is happening with just visiting regular reddit and having ad/tracker blockers on, getting an error about my User Agent not being proper. Looks like Reddit finally swung the axe on third party APIs.

**Comment by SebiTalent04** [comment]
Happens again after the yesterday's reddit downtime, on all instances. Fuck u/spez.
