### ISSUE TITLE
The future of Libreddit

### ISSUE THREAD

**Issue by freedit-dev** [libreddit/libreddit#871]
In response to Reddit's recent restrictions on non-logged-in users, several strategies have been discussed to maintain access while preserving user privacy and efficiency.

The first strategy involves **client-side access**. Users can leverage their local browsers, circumventing the need for server relay. This approach offers notable benefits, including the absence of IP restrictions, enhanced speed, and unrestricted browsing. While this method does expose the user's IP to Reddit, potentially compromising privacy, it still offers a faster and more private experience compared to direct Reddit access. Theoridically, it just needs every user to download a binary and run it locally. I think this is the best solution. Unfortunately, the Libreddit author seems to be so pessimistic about this solution to mention it in the README(instead they just told users that this project is dead).

The second method is also direct client access, but users don't need to locally install LIbreddit; instead, they use the web version, like the wasm version. That needs developers' great effort.

The third strategy focuses on developing a **SOCKS proxy** (#841 ) that utilizes services like Cloudflare Warp or the Tor network. I'm working on this and it worked well at the moment. There is a tor-embedded fork and it works well https://git.spec.cat/Nyaaori/libreddit

Lastly, someone suggests **integrating an account system**. Theoretically, access to Reddit should be feasible with an account. However, this method is not foolproof, as Reddit could still potentially impede access through IP detection and blocking mechanisms. Implementing an account system could allow users to navigate Reddit's restrictions, but it also risks being undermined by Reddit's ability to detect and block based on IP addresses. And it requires developer to make it happen.

If you are not interested in the technical details, just want to get rid of the shitty Reddit UI, you can just:

1. Download the binary from release page, run locally.
2. Or use the tor-embedded fork https://git.spec.cat/Nyaaori/libreddit
3. Or use the SOCKS proxy instance like https://libreddit.freedit.eu/

For maintainers and developers, I just want to say thank you for your work. And please, don't give up, don't let Reddit win, don't tell us in Readme that this project is dead. We need you, we need Libreddit. We need a better Reddit experience.

**Comment by pixelpassport** [comment]
Can anyone help me build the docker container for the tor-embedded fork? I'm sure it's user-error, I've only used pre-built containers in docker until now. I get an error with 'tor_netdoc'. 

```180.8 error[E0308]: mismatched types
180.8    --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tor-circmgr-0.9.1/src/usage.rs:114:17
180.8     |
180.8 114 |             v4: relay.ipv4_policy(),
180.8     |                 ^^^^^^^^^^^^^^^^^^^ expected `PortPolicy`, found a different `PortPolicy`
180.8     |
180.8     = note: `PortPolicy` and `PortPolicy` have similar names, but are actually distinct types
180.8 note: `PortPolicy` is defined in crate `tor_netdoc`
180.8    --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tor-netdoc-0.9.1/src/types/policy/portpolicy.rs:35:1
180.8     |
180.8 35  | pub struct PortPolicy {
180.8     | ^^^^^^^^^^^^^^^^^^^^^
180.8 note: `PortPolicy` is defined in crate `tor_netdoc`
180.8    --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tor-netdoc-0.8.3/src/types/policy/portpolicy.rs:35:1
180.8     |
180.8 35  | pub struct PortPolicy {
180.8     | ^^^^^^^^^^^^^^^^^^^^^
180.8     = note: perhaps two different versions of crate `tor_netdoc` are being used?
180.8
180.9 error[E0308]: mismatched types
180.9    --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tor-circmgr-0.9.1/src/usage.rs:115:17
180.9     |
180.9 115 |             v6: relay.ipv6_policy(),
180.9     |                 ^^^^^^^^^^^^^^^^^^^ expected `PortPolicy`, found a different `PortPolicy`
180.9     |
180.9     = note: `PortPolicy` and `PortPolicy` have similar names, but are actually distinct types
180.9 note: `PortPolicy` is defined in crate `tor_netdoc`
180.9    --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tor-netdoc-0.9.1/src/types/policy/portpolicy.rs:35:1
180.9     |
180.9 35  | pub struct PortPolicy {
180.9     | ^^^^^^^^^^^^^^^^^^^^^
180.9 note: `PortPolicy` is defined in crate `tor_netdoc`
180.9    --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tor-netdoc-0.8.3/src/types/policy/portpolicy.rs:35:1
180.9     |
180.9 35  | pub struct PortPolicy {
180.9     | ^^^^^^^^^^^^^^^^^^^^^
180.9     = note: perhaps two different versions of crate `tor_netdoc` are being used?```

**Comment by FireMasterK** [comment]
I still think solutions like #819 and the GraphQL API are the way forward. IP rotation could also be done to lower risks of detections, but I don't think is necessary currently.

**Comment by wsy2220** [comment]
I just want a cleaner reddit. So I let libreddit to send my cookies, which works fine.

**Comment by sigaloid** [comment]
> I still think solutions like #819 and the GraphQL API are the way forward. IP rotation could also be done to lower risks of detections, but I don't think is necessary currently.

This is what i'll end up merging when i fork it. 

Sorry for the radio silence and only intermittent messages - I've been linking that fork to a few users and they're saying it's working now. So i'll be forking it all and accepting the backlogged contributions. Reason for fork and not just updating this, is that other maintainers are not as willing to merge this due to legal issues

**Comment by freedit-dev** [comment]
@sigaloid Oh, sorry. I missed your work on the Android Oauth fork. I'll take a look at it and see if I can get it working.

And I holp the main repo could release binary package for Windows and Mac OS X. So for users who just want a better UI, they could use it on their personal computer without compiling. You could refer to this GitHub Actions workflow file: <https://github.com/freedit-dev/libreddit/blob/master/.github/workflows/release.yml>

By the way, tor doesn't have to be bundled with libreddit. It could be installed separately and work as a socket proxy. Just see <https://gitlab.torproject.org/tpo/core/arti>

**Comment by sigaloid** [comment]
I think a feature addition for the arti wouldn't be a bad idea. Just as an option to add onto it

**Comment by sigaloid** [comment]
Okay, I've gotten around to it. https://github.com/redlib-org/redlib

Ended up using my original OAuth spoofing. Will be looking into adding Tor (https://github.com/redlib-org/redlib/issues/1)

**Comment by rndmh3ro** [comment]
> Okay, I've gotten around to it. https://github.com/redlib-org/redlib
> 
> Ended up using my original OAuth spoofing. Will be looking into adding Tor ([redlib-org/redlib#1](https://github.com/redlib-org/redlib/issues/1))

I just tested redlib, as my instance was banned by reddit some weeks ago.

I used it as a drop-in replacement for libreddit on my running instance. I built redlib and replaced libreddit binary with redlib and now it works again. That's awesome, thanks!

**Comment by throwaway-d** [comment]
I saw this interesting idea: https://codeberg.org/teddit/teddit/issues/427
But @sigaloid got the solution already!
